#!/bin/bash

# mindevenviro-windows search

# I use dos2unix to convert file endings

###     WARNING:    DON'T EDIT ANYTHING BELOW	###

set -x

LANG="C";
IFS="$(echo -en "\n\b")" ;
FILE="search";
line='';
pause=0;
readonly empty='' ;

			if [[ "$EUID" != 0 ]] ;
		then
	echo -e "sudo search -h :: please\n" ;
	help_function ;
else

# temp folder
		if [[ "$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" != '' ]] ;
	then
		tmpfolder="$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" ;
	else
		tmpfolder="/tmp" ;
fi
# temp folder END

touch $tmpfolder/line.search ;

help_function(){
echo -e "\nUsage: sudo search [-s|--search] [PATH] [TOSEARCH] [TOGREP] [TOEXCLUDE]\n
SEARCH THE DRIVE\n
 This script searches your drive\r
 for everything in it, and displays on the Terminal.\r
 Finds: log files, example code, .conf to edit...\n
 [PATH]: the absolute path like: /var/
 [TOSEARCH]: search pattern\r
 [TOGREP]: search a word in file\r
 [TOEXCLUDE]: a word you want to exclude from your search results.\n" ;
exit 0 ;
}

searchStat(){
echo "searchStat function"
	echo -e "search $(date) :: as $SUDO_USER :: in $(uname -n) :: $path $exclud3 $togrep $exclud3 ::" >>"/home/$SUDO_USER/.wH0rUNSon" && wait ;
}

#exithandler
exitHandl3R(){
echo "exitHandl3R function"
	searchStat;
	pgrep $FILE | awk "{print $1}" | xargs kill -15 && wait && 
	pgrep less | awk "{print $1}" | xargs kill -15 && wait &&
	pgrep nano | awk "{print $1}" | xargs kill -15 && wait &&
	pgrep mupdf | awk "{print $1}" | xargs kill -15 && wait ;
	echo -e "\n ... good bye $SUDO_USER" ;
	exit 0 ;
}

display(){
echo "display function"
# display	
			# uS3F is the owner of the file
			uS3F=$(ls -sl "$line" | awk '{print $4}' | tr -d '\ ');
###
			if [[ $(echo "$line" | xargs file) != $empty ]]
		then
			if [[ ! $(echo "$line" | xargs file) =~ PDF ]] && [[ ! $(echo "$line" | xargs ls) =~ .conf ]] ;
		then
			pause=1 ;
			sudo -u "$uS3F" less "$line" && return ;
		else
			if [[ $(dpkg -l | grep mupdf | awk '{print $2}') != '' ]] && [[ $(echo "$line" | xargs file) =~ PDF ]] ;
		then
			pause=1 ;
			sudo -u "$uS3F" mupdf "$line" && return ;
		else
			pause=1 ;
			echo -e " ... no PDF viewer installed, or you are in Windows \r" ;
			echo -e " ... $(echo $line | xargs file) :: - nothing to show\r" ;
		fi
	fi
###
			if [[ $(echo "$line" | xargs ls) =~ .conf ]] ;
		then
			echo -e " ... do you want to edit $line ?, type ok, or just hit return if not." && read -p -r ;
			
				if [[ $REPLY = "ok" ]];
			then
				pause=1 ;
				sudo -u "$uS3F" nano "$line" && return ;
			else
				if [[ ! $(echo "$line" | xargs file) =~ PDF|PHP|script|ASCII|text|TEXT|HTML|XML ]] ;
			then
				pause=0 ;
				echo -e " ... no PDF|PHP|script|ASCII|text|TEXT|HTML|XML \r" ;
			else
				pause=0 ;
				echo -e " ... $(echo $line | xargs file) :: - nothing to show\r" ;
		fi
	fi
fi
				else
					return ;
fi
###
#display END
}

# search query
eingabe(){
echo "eingabe function"

		trap 'exitHandl3R' SIGINT ;

		while read line
	do
		if [[ $pause = 1 ]] ;
	then
		if [[ "$togrep" != '' ]] && [[ "$exclud3" = '' ]] ;
	then
		cat $line | grep -E $togrep >| "$tmpfolder/line.search" ;
		line="$tmpfolder/line.search" ;
		read -p -r "continue? ";
		display ;

		elif [[ "$exclud3" != '' ]] && [[ "$togrep" != '' ]] ;
	then
		cat $line | grep -E $togrep | grep -vE $exclud3 >| "$tmpfolder/line.search" ;
		line="$tmpfolder/line.search" ;
		read -p -r "continue? " ; 
		display ;
	fi
fi
		if [[ $pause = 0 ]] ;
	then
		if [[ "$togrep" != '' ]] && [[ "$exclud3" = '' ]] ;
	then
		cat $line | grep -E $togrep >| "$tmpfolder/line.search" ;
		line="$tmpfolder/line.search" ;
		display ;

		elif [[ "$exclud3" != '' ]] && [[ "$togrep" != '' ]] ;
	then
		cat $line | grep -E $togrep | grep -vE $exclud3 >| "$tmpfolder/line.search" ;
		line="$tmpfolder/line.search" ;
		display ;
	fi
fi
done<<<"$line";
}
# search query		END#

# Main function
main(){
echo "main function"
searchP4th="$2";
searchP4ttern="$3";
togrep="$4";
exclud3="$5";

			if [[ "$togrep" != '' ]] || [[ "$exclud3" != '' ]] ;
		then
				for line in $(find $searchP4th -name *$searchP4ttern* -type f) ;
			do
				eingabe ;
			done
	else
			help_function ;
fi
}

# ASK
  case "$1" in
		-s|--search)
        toshiffta=0 ;
        shift "$toshiffta" ;		
		main "$@" ;
        ;;
        -h|--help)
        toshiffta=0 ;
        shift "$toshiffta" ;
		help_function "$@" ;
        ;;
esac
# ASK END
fi
