#!/bin/bash
# mindevenviro-windows search
###     WARNING:    DON'T EDIT ANYTHING BELOW	###

LANG="C";
IFS="$(echo -en "\n\b")" ;
FILE="search";
line='';
lines='';
			if [[ "$EUID" != 0 ]] ;
		then
	echo -e "sudo search -h :: please\n" ;
else

display(){
# display
trap 'exitHandl3R' SIGINT ;

		while read line ;
	do
		wait ;
###main	
		if [[ $(echo "$line" | xargs file) =~ PDF|PHP|script|ASCII|text|TEXT|HTML|XML ]] ;
	then
###2
			if [[ "$tosearCH" != '' ]] ;
		then
			# uS3F is the owner of the file
			uS3F=$(ls -sl "$line" | awk '{print $4}' | tr -d '\ ');
			
			if [[ ! $(echo "$line" | xargs file) =~ PDF ]] && [[ ! $(echo "$line" | xargs file) =~ .conf ]] ;
		then
			sudo -u "$uS3F" less $line;
			pause=1 ;
		else
			if [[ $(dpkg -l | grep mupdf | awk '{print $2}') != '' ]] && [[ $(echo "$line" | xargs file) =~ PDF ]] ;
		then
			sudo -u "$uS3F" mupdf $line 2>/dev/null ;
			pause=1 ;
		else
			echo -e " ... no PDF viewer installed, or you are in Windows \r" ;
			echo -e " ... $(echo $line | xargs file) :: - nothing to show\r" ;
			pause=0 ;
		fi
	fi
			if [[ $(echo "$line" | xargs file) =~ .conf ]] ;
		then
			echo -e " ... do you want to edit $line ?, type ok, or just hit return if not." && read -p ;
			
			if [[ $REPLY = "ok" ]];
		then
			sudo -u "$uS3F" nano $line;
			pause=1 ;
		else
			if [[ ! $(echo "$line" | xargs file) =~ PDF|PHP|script|ASCII|text|TEXT|HTML|XML ]] ;
		then
			echo -e " ... no PDF|PHP|script|ASCII|text|TEXT|HTML|XML \r" ;
			pause=0 ;
		else
			echo -e " ... $(echo $line | xargs file) :: - nothing to show\r" ;
			pause=0 ;
			fi	
		fi
	fi
fi
###2
	done <<<"$lines" ;

#display END
}

#exithandler
exitHandl3R(){
	searchStat ;
	pgrep $FILE | awk "{print $1}" | xargs kill -9 && pgrep less | awk "{print $1}" | xargs kill -9;
}

# search query
preP4re(){
		while read line ;
	do
		if [[ $pause = 1 ]] ;
	then
		line=$lines ;
		read -r -p "continue? " && display && wait ;
	else
		line=$lines ;
		display && wait ;
	fi ;
done < <(find "$searchQuery")
}
# search query END

eingabe(){
pause=0 ;
		if [[ "$togrep" != '' ]] && [[ "$exclud3" = '' ]] && [[ "$togrep" != "-g" ]] && [[ "$exclud3" != "-e" ]] ;
	then
		searchQuery="/ -name \"*\" -type f | grep -E $togrep" ;

		elif [[ "$exclud3" != '' ]] && [[ "$togrep" != '' ]] && [[ "$togrep" != "-g" ]] && [[ "$exclud3" != "-e" ]] ;
	then
		searchQuery="/ -name \"*\" -type f | grep -E $togrep| grep -vE $exclud3" ;
fi
tosearCH=$line ;
preP4re ;
}

searchStat(){
	echo -e "search $(date) :: as $SUDO_USER :: in $(uname -n) :: $path $exclud3 $togrep $exclud3 ::" >>"/home/$SUDO_USER/.wH0rUNSon" && wait ;
}

help_function(){echo -e "\n USAGE: sudo search -s SEARCHPATTERN -g TOGREP -e TOEXCLUDE \n";}

# Main function
main(){
togrepFlag="$2";
togrep="3"
exclud3Flag="4";
exclud3="$5"
			if [[ "$togrepFlag" = "-g" ]] && [[ "$exclud3Flag" = '' ]]
		then
			eingabe ;

			elif [[ "$togrepFlag" = "-g" ]] && [[ "$exclud3Flag" = "-e" ]] ;
		then
			eingabe ;

			elif [[ "$exclud3Flag" = "-e" ]] || [[ "$togrepFlag" = "-g" ]] ;
		then
			eingabe ;
	else
			help_function ;
fi
}

# ASK
  case "$1" in
		-s|--search)
        toshiffta=0 ;
        shift "$toshiffta" ;		
		main "$@" ;
        ;;
        -h|--help)
        toshiffta=0 ;
        shift "$toshiffta" ;
		help_function "$@" ;
        ;;
esac
# ASK END
fi
