#!/bin/bash

# mindevenviro-windows search

# I use dos2unix to convert file endings

###     WARNING:    DON'T EDIT ANYTHING BELOW	###

set -x

LANG="C";
IFS="$(echo -en "\n\b")" ;
FILE="search";
line='';
todisplay='';
			if [[ "$EUID" != 0 ]] ;
		then
	echo -e "sudo search -h :: please\n" ;
	help_function ;
else

display(){
# display
trap 'exitHandl3R' SIGINT ;

		while true ;
	do
		wait ;
			# uS3F is the owner of the file
			uS3F=$(ls -sl "$todisplay" | awk '{print $4}' | tr -d '\ ');
###
			if [[ ! $(echo "$todisplay" | xargs file) =~ PDF ]] && [[ ! $(echo "$todisplay" | xargs ls) =~ .conf ]] ;
		then
			sudo -u "$uS3F" less $line;
			pause=1 ;
		else
			if [[ $(dpkg -l | grep mupdf | awk '{print $2}') != '' ]] && [[ $(echo "$todisplay" | xargs file) =~ PDF ]] ;
		then
			sudo -u "$uS3F" mupdf $line 2>/dev/null ;
			pause=1 ;
		else
			echo -e " ... no PDF viewer installed, or you are in Windows \r" ;
			echo -e " ... $(echo $line | xargs file) :: - nothing to show\r" ;
			pause=0 ;
		fi
	fi
###
			if [[ $(echo "$todisplay" | xargs ls) =~ .conf ]] ;
		then
			echo -e " ... do you want to edit $line ?, type ok, or just hit return if not." && read -p ;
			
				if [[ $REPLY = "ok" ]];
			then
				sudo -u "$uS3F" nano $line;
				pause=1 ;
			else
				if [[ ! $(echo "$todisplay" | xargs file) =~ PDF|PHP|script|ASCII|text|TEXT|HTML|XML ]] ;
			then
				echo -e " ... no PDF|PHP|script|ASCII|text|TEXT|HTML|XML \r" ;
				pause=0 ;
			else
				echo -e " ... $(echo $line | xargs file) :: - nothing to show\r" ;
				pause=0 ;
		fi
	fi
fi
###
done <<<"$todisplay";
#display END
}

#exithandler
exitHandl3R(){

	searchStat;
	pgrep $FILE | awk "{print $1}" | xargs kill -9 && pgrep less | awk "{print $1}" | xargs kill -9;
}

# search query
eingabe(){
pause=0 
		while read line
	do
		if [[ $pause = 1 ]] ;
	then
		if [[ "$togrep" != '' ]] && [[ "$exclud3" = '' ]] ;
	then
		todisplay="$(cat $line | grep -E $togrep)" ;
		read -r -p "continue? " && display && wait ;

		elif [[ "$exclud3" != '' ]] && [[ "$togrep" != '' ]] ;
	then
		todisplay="$(cat $line | grep -E $togrep | grep -vE $exclud3)" ;
		read -r -p "continue? " && display && wait ;
	fi
fi
		if [[ $pause = 0 ]] ;
	then
		if [[ "$togrep" != '' ]] && [[ "$exclud3" = '' ]] ;
	then
		todisplay="$(cat $line | grep -E $togrep)" ;
		display && wait ;

		elif [[ "$exclud3" != '' ]] && [[ "$togrep" != '' ]] ;
	then
		todisplay="$(cat $line | grep -E $togrep | grep -vE $exclud3)" ;
		display && wait ;
	fi
fi
done <<<"$(find $searchP4th -name *$searchP4ttern* -type f)";
}
# search query		END#

searchStat(){
	echo -e "search $(date) :: as $SUDO_USER :: in $(uname -n) :: $path $exclud3 $togrep $exclud3 ::" >>"/home/$SUDO_USER/.wH0rUNSon" && wait ;
}

help_function(){
echo -e "Usage: search [-s|--search] [PATH] [TOSEARCH] [TOGREP] [TOEXCLUDE]\r
sudo this script:\r
SEARCH THE DRIVE\n
 This script searches your drive\r
 for everything in it, and displays\r
 only text in the less viewer.\r
 Finds: log files, example code, etc.\n
 [PATH]: the absolute path like: /var/
 [TOSEARCH]: search pattern\r
 [TOGREP]: search a word in file\r
 [TOEXCLUDE]: a word you want to exclude from your search results.\n" ;
exit 0 ;
}

# Main function
main(){
searchP4th="$2";
searchP4ttern="$3";
togrep="$4";
exclud3="$5";

			if [[ "$togrep" != '' ]] || [[ "$exclud3" != '' ]] ;
		then
			eingabe ;
	else
			help_function ;
fi
}

# ASK
  case "$1" in
		-s|--search)
        toshiffta=0 ;
        shift "$toshiffta" ;		
		main "$@" ;
        ;;
        -h|--help)
        toshiffta=0 ;
        shift "$toshiffta" ;
		help_function "$@" ;
        ;;
esac
# ASK END
fi
